server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdb
    username: postgres
    password: 151859140
  flyway:
    url: jdbc:postgresql://localhost:5432/restaurantdb
    enabled: true
    user: postgres
    password: 151859140
    table: flyway_schema_history_restaurant_db
    baseline-on-migrate: true
  doc:
    swagger-ui:
      path: /swagger-ui.html
  mail:
    host: smtp.gmail.com
    port: 587
    username: muhammetylmz278@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 10000
  cache:
    ttl: 30
    promise-ttl: 60
    type: redis

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumers:
      default-group-id: group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

application:
  description: restaurant
  version: 1.0

minio:
  bucket:
    name: deneme
  access:
    name: root
    secret: password
  url: http://127.0.0.1:9000

token:
  access-expire-minute: 200
  issuer: restaurant

app-context: http://localhost:8081